server:
  port: 9080

spring:
  application:
    name: mk-approve
  datasource:
       url: jdbc:mysql://120.24.189.102:3306/approve?useUnicode=true&characterEncoding=utf8&useSSL=false
       username: root
       password: nfdw@123
       driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.mk.approve.entity  # 注意：对应实体类的路径

